import "Aspects_VFX.lua"

local file = rom.path.combine(rom.paths.Content, 'Game/Projectiles/PlayerProjectiles.sjson')
	sjson.hook(file, function(data)
	-- Axe Aspect of Young Mel special 
    table.insert(data.Projectiles,
	{
		Name = "ProjectileAxeBlockSpin",
		InheritFrom = "1_BaseDamagingProjectile",
		DetonateFx = "AxeDeflectBase",
		Type = "STRAIGHT",
		TotalFuse = 0.4,
		Fuse = 0.2,
		FuseStart = 0,
		ImmunityDuration = 0.3,
		MultiDetonate = true,
		AffectsEnemies = true,
		AffectsFriends = false,
		Speed = 160,
		Range = 650.0,
		DamageRadius = 100,
		DamageRadiusScaleY = 0.62,
		RequireHitCenter = false,
		AttachToOwner = false,
		NumPenetrations = 9999,
		AffectsSelf = false,
		CheckUnitImpact = false,
		CheckObstacleImpact = true,
		UnlimitedUnitPenetration = true,
		Damage = 20,
		ImpactVelocity = 0,
		UseArmor = false,
		UseVulnerability = false,
		UseDetonationForProjectileDefense = true,
		UseRadialImpact = true,
		Thing =
		{
			Graphic = "AxeDeflectBase",
			OffsetZ = 70,
			Grip = 999999,
		},
		Effects =
		{
			{
				Name = "OnHitStun",
				Duration = 0.7,
				DisableMove = true,
				DisableRotate = true,
				DisableAttack = true,
				Active = true,
				CanAffectInvulnerable = false,
				FrontFx = "null",
			},
		},
	})
    -- Axe Aspect of Young Mel special with "Mirror Shield Hammer"
	table.insert(data.Projectiles,
	{
		Name = "ProjectileAxeBlockSpinDeflect",
		InheritFrom = "1_BaseDamagingProjectile",
		DetonateFx = "AxeDeflectBase",
		Type = "STRAIGHT",
		TotalFuse = 0.4,
		Fuse = 0.2,
		FuseStart = 0,
		ImmunityDuration = 0.3,
		MultiDetonate = true,
		AffectsEnemies = true,
		AffectsFriends = false,
		Speed = 160,
		Range = 650.0,
		DamageRadius = 100,
		DamageRadiusScaleY = 0.62,
		RequireHitCenter = false,
		AttachToOwner = false,
		NumPenetrations = 9999,
		AffectsSelf = false,
		CheckUnitImpact = false,
		CheckObstacleImpact = true,
		UnlimitedUnitPenetration = true,
		Damage = 20,
		ImpactVelocity = 0,
		UseArmor = false,
		UseVulnerability = false,
		UseDetonationForProjectileDefense = true,
		UseRadialImpact = true,
		ProjectileDefenseRadius = 100,
		DeflectProjectiles = true,
		SilentImpactOnInvulnerable = true,
		ImpactFx = "AthenaProjectileImpact",
		Thing =
		{
			Graphic = "AxeDeflectBase",
			OffsetZ = 70,
			Grip = 999999,
		},
		Effects =
		{
			{
				Name = "OnHitStun",
				Duration = 0.7,
				DisableMove = true,
				DisableRotate = true,
				DisableAttack = true,
				Active = true,
				CanAffectInvulnerable = false,
				FrontFx = "null",
			},
		},
	})
    -- Staff Aspect of Young Mel special
	table.insert(data.Projectiles,
	{
		Name = "ProjectileStaffBoltEA",
		InheritFrom = "1_BaseDamagingProjectile",
		Type = "HOMING",
		HomingAllegiance = "ENEMIES",
		AdjustRateAcceleration = 3000,
		MaxAdjustRate = 100,
		SpinRate = 0,
		Speed = 0,
		Acceleration = 2000,
		Range = 880.0,
		Damage = 20,
		DetonateFx = "QuickFlashEnemy",
		CheckObstacleImpact = true,
		CheckUnitImpact = true,
		UnlimitedUnitPenetration = false,
		DetonateAtVictimLocation = true,
		Thing =
		{
			Graphic = "StaffBallProjectile",
			AttachedAnim = "StaffProjectileShadow",
			OffsetZ = 112,
			Grip = 999999,
			RotateGeometry = true,
			Tallness = 20,
			Points =
			{
				{
					X = 76,
					Y = 20,
				},
				{
					X = 76,
					Y = -20,
				},
				{
					X = -32,
					Y = -20,
				},
				{
					X = -32,
					Y = 20,
				},
			},
		},
	})
    -- Dagger Aspect of Young Mel special
	table.insert(data.Projectiles,
	{
		Name = "ProjectileDaggerThrowEA",
		InheritFrom = "1_BaseDamagingProjectile",
		DetonateFx = "null",
		Type = "HOMING",
		AffectsEnemies = true,
		AffectsFriends = false,
		AffectsSelf = false,
		CheckUnitImpact = true,
		CheckObstacleImpact = true,
		UnlimitedUnitPenetration = false,
		NumPenetrations = 0,
		AttachToOwner = false,
		StartDelay = 0.04,
		Damage = 25,
		Speed = 6000,
		Range = 830,
		UseRadialImpact = false,
		UseArmor = true,
		UseVulnerability = true,
		DissipateFx = "null",
		GroupName = "Standing",
		ClearOnAttackEffects = true,
		ImpactFx = "DaggerProjectileImpactFx",
		DeathFx = "DaggerProjectileFxFade",
		ProjectileDefenseRadius = 45,
		Thing =
		{
			Graphic = "DaggerProjectileFxBrown",
			OffsetZ = 70,
			RotateGeometry = true,
			Grip = 999999,
			Points =
			{
				{
					X = 35,
					Y = 25,
				},
				{
					X = 35,
					Y = -25,
				},
				{
					X = -5,
					Y = -25,
				},
				{
					X = -5,
					Y = 25,
				},
			},
		},
		Effects =
		{
			 {
				Name = "OnHitStunHeavy",
				Duration = 1.1,
				DisableMove = true,
				DisableRotate = true,
				DisableAttack = true,
				Active = true,
				CanAffectInvulnerable = false,
				FrontFx = "null",
			},
		},
	})

	table.insert(data.Projectiles,
	{
		Name = "ProjectileCastYM",
		InheritFrom = "1_BaseDamagingProjectile",
		Type = "INSTANT",
		Range = 0.0,
		FuseStart = 3.0,
		Fuse = 3,
		Damage = 0,
		ArmedExpirationDamage = 150,
		ArmedGraphic = "CastCircleArmed",
		DamageRadius = 430,
		DamageRadiusScaleY = 0.5,
		BlastSpeed = 2000,
		AnimIgnoreBlastRadius = true,
		HideGraphicOnDetonate = true,
		ExpandBlastDuringDetonation = true,
		CheckUnitImpact = false,
		CheckObstacleImpact = false,
		ImpactVelocity = 0,
		RequireHitCenter = false,
		ImpactFx = "CastCircleUnitFxFront",
		ArmedImpactFx = "GraspingHandsAttack",
		DeathFx = "null",
		DetonateFx = "CastCircleOut",
		SpeedMultiplierOfEnemyProjectilesInside = 1.0,
		GroupName = "FX_Terrain",
		UseStartLocation = true,
		SpawnType = "PROJECTILE",
		SilentImpactOnInvulnerable = true,
		UseAttachedToTimeMultiplier = false,
		IgnoreCoverageAngles = true,
		Thing =
		{
			Graphic = "CastCircleIn",
			OffsetZ = 0,
			Tallness = 50,
			AttachedAnim = "null",
			Grip = 999999,
			RotateGeometry = true,
			Points =
			{
				{
					X = 32,
					Y = 16,
				},
				{
					X = 32,
					Y = -16,
				},
				{
					X = -32,
					Y = -16,
				},
				{
					X = -32,
					Y = 16,
				},
			},
		},
	})

	table.insert(data.Projectiles,
	{
		Name = "ProjectileCastHammerYM",
		InheritFrom = "1_BaseDamagingProjectile",
		Type = "INSTANT",
		Range = 0.0,
		FuseStart = 3.0,
		Fuse = 3,
		Damage = 0,
		ArmedExpirationDamage = 150,
		ArmedGraphic = "CastCircleArmed",
		DamageRadius = 430,
		DamageRadiusScaleY = 0.5,
		BlastSpeed = 2000,
		AnimIgnoreBlastRadius = true,
		HideGraphicOnDetonate = true,
		ExpandBlastDuringDetonation = true,
		CheckUnitImpact = false,
		CheckObstacleImpact = false,
		ImpactVelocity = 0,
		RequireHitCenter = false,
		ImpactFx = "CastCircleUnitFxFront",
		ArmedImpactFx = "GraspingHandsAttack",
		DeathFx = "null",
		DetonateFx = "CastCircleOut",
		SpeedMultiplierOfEnemyProjectilesInside = 1.0,
		GroupName = "FX_Terrain",
		UseStartLocation = true,
		SpawnType = "PROJECTILE",
		SilentImpactOnInvulnerable = true,
		UseAttachedToTimeMultiplier = false,
		IgnoreCoverageAngles = true,
		Thing =
		{
			Graphic = "CastCircleIn",
			OffsetZ = 0,
			Tallness = 50,
			AttachedAnim = "null",
			Grip = 999999,
			RotateGeometry = true,
			Points =
			{
				{
					X = 32,
					Y = 16,
				},
				{
					X = 32,
					Y = -16,
				},
				{
					X = -32,
					Y = -16,
				},
				{
					X = -32,
					Y = 16,
				},
			},
		},
	})

	table.insert(data.Projectiles,
	{
		Name = "ProjectileCastLobYM",
		InheritFrom = "1_BaseDamagingProjectile",
		Type = "LOB",
		DamageRadius = 400,
		MaxAdjustRate = 60,
		AutoAdjustForTarget = true,
		SpinRate = -360,
		Speed = 1200,
		Gravity = 2000,
		MinRange = 0.0,
		Range = 600,
		LaunchAngle = 30,
		UseStartLocation = false,
		DetonateAtTarget = true,
		DetonateFx = "RadialNovaDionysus",
		--ImpactFx = "PoseidonCastBoonFx",
		--DetonateFx = "PoseidonCastBoonFx",
		--ReflectFx = "GrenadeBounceSpark",
		CheckUnitImpact = false,
		CheckObstacleImpact = true,
		Damage = 30,
		DamageRadiusScaleY = 1,
		BlastSpeed = 3000,
		ImpactVelocity = 0,
		DeathFx = "null",
		UseVulnerability = false,
		GroupName = "Standing",
		SilentImpactOnInvulnerable = true,
		IgnoreCoverageAngles = true,
		UseRadialImpact = false,
		Thing =
		{
			Graphic = "DionysusLobProjectile",
			--Graphic = "PoseidonSprintBallIn",
			--AttachedAnim = "MedusaShadow",
			OffsetZ = 112,
			Tallness = 50,
			AttachedAnim = "GrenadierShadow",
			Grip = 999999,
			RotateGeometry = true,
			Points =
			{
				{
					X = 100,
					Y = 50,
				},
				{
					X = 100,
					Y = -50,
				},
				{
					X = -32,
					Y = 0,
				},
			},
		},
		Effects =
		{
			{
				Name = "OnHitStun",
				Duration = 0.7,
				DisableMove = true,
				DisableRotate = true,
				DisableAttack = true,
				Active = true,
				CanAffectInvulnerable = false,
			},
		},
	})

	table.insert(data.Projectiles,
	{
		Name = "ProjectileCastLobChargeYM",
		InheritFrom = "1_BaseDamagingProjectile",
		Type = "LOB",
		DamageRadius = 400,
		MaxAdjustRate = 60,
		AutoAdjustForTarget = true,
		SpinRate = -360,
		Speed = 1200,
		Gravity = 2000,
		MinRange = 0.0,
		Range = 600,
		LaunchAngle = 30,
		UseStartLocation = false,
		DetonateAtTarget = true,
		DetonateFx = "RadialNovaDionysus",
		--ImpactFx = "PoseidonCastBoonFx",
		--DetonateFx = "PoseidonCastBoonFx",
		--ReflectFx = "GrenadeBounceSpark",
		CheckUnitImpact = false,
		CheckObstacleImpact = true,
		Damage = 30,
		DamageRadiusScaleY = 1,
		BlastSpeed = 3000,
		ImpactVelocity = 0,
		DeathFx = "null",
		UseVulnerability = false,
		GroupName = "Standing",
		SilentImpactOnInvulnerable = true,
		IgnoreCoverageAngles = true,
		UseRadialImpact = false,
		Thing =
		{
			Graphic = "DionysusLobProjectile",
			--Graphic = "PoseidonSprintBallIn",
			--AttachedAnim = "MedusaShadow",
			OffsetZ = 112,
			Tallness = 50,
			AttachedAnim = "GrenadierShadow",
			Grip = 999999,
			RotateGeometry = true,
			Points =
			{
				{
					X = 100,
					Y = 50,
				},
				{
					X = 100,
					Y = -50,
				},
				{
					X = -32,
					Y = 0,
				},
			},
		},
		Effects =
		{
			{
				Name = "OnHitStun",
				Duration = 0.7,
				DisableMove = true,
				DisableRotate = true,
				DisableAttack = true,
				Active = true,
				CanAffectInvulnerable = false,
			},
		},
	})

	return data
	end)