local file = rom.path.combine(rom.paths.Content, 'Game/Weapons/PlayerWeapons.sjson')
	sjson.hook(file, function(data)
	for key, weapon in pairs(data.Weapons) do
		if weapon.Name == 'WeaponAxeSpecial' then
			weapon.Effects =
			{
				{
					Name = "AxeSpecialBlockSelfTriggerLock",
					Duration = 0.30,
					Active = true,
				},
				{
					Name = "AxeSpecialDisable",
					Duration = 0.31,
					DisableAttack = true,
					DisableMove = true,
					DisableRotate = true,
					RequestTriggerLock = true,
					Cancelable = false,
					Active = true,
				},
				{
					Name = "AxeSpecialDisableCancelable",
					Duration = 0.37,
					DisableAttack = true,
					DisableMove = true,
					DisableRotate = true,
					RequestTriggerLock = true,
					Cancelable = true,
					Active = true,
				},
				{
					Name = "AxeSpecialDisableMovementCancelable",
					Duration = 0.38,
					DisableAttack = false,
					DisableMove = true,
					DisableRotate = true,
					RequestTriggerLock = true,
					Cancelable = true,
					Active = true,
				},
				{
					Trigger = "Charging",
					Name = "AspectSlowCharge",
					Type = "SPEED",
					DurationFrames = 30,
					Modifier = 0.5,
					Cancelable = true,
					Active = false,
					CanAffectInvulnerable = true,
				},
				{
					Trigger = "Charging",
					Name = "AspectSlowFire",
					Type = "SPEED",
					DurationFrames = 60,
					Modifier = 0.5,
					Cancelable = true,
					Active = false,
					CanAffectInvulnerable = true,
				},
				{
					Trigger = "Charging",
					Name = "ShieldSelfSpeed",
					Type = "SPEED",
					HaltOnStart = true,
					Duration = 0.02,
					Modifier = 0.2,
					Active = false,
					CanAffectInvulnerable = true,
					
				},
				{
					Trigger = "Charging",
					Name = "ShieldSelfInvulnerableRush",
					Type = "INVULNERABLE",
					Duration = 0.1,
					Modifier = 1.0,
					Active = false,
					CanAffectInvulnerable = true,
					ClearOnAttack = true,
				},
				{
					Trigger = "Fire",
					Name = "ShieldSelfInvulnerableRush2",
					Type = "INVULNERABLE",
					DurationFrames = 34,
					Modifier = 1.0,
					Active = false,
					AngleCoverage = 220,
					CanAffectInvulnerable = true,
					Cancelable = true,
				},
				{
					Name = "ShieldFireDisableAttack",
					DurationFrames = 13,
					DisableAttack = true,
					RequestTriggerLock = true,
					Cancelable = false,
					Active = false,
				},
				{
					Trigger = "Charging",
					Name = "ShieldChargeDisableMove",
					DurationFrames = 19,
					DisableMove = true,
					DisableRotate = true,
					Cancelable = true,
					TimeModifierFraction = 0,
					ClearOnAttack = true,
					Active = false,
				},
				{
					Trigger = "Fire",
					Name = "ShieldFireDisableMove2",
					DurationFrames = 34,
					DisableMove = true,
					DisableRotate = true,
					Cancelable = true,
					TimeModifierFraction = 0,
					Active = false,
				},
			}
	
		--elseif weapon.Name == 'WeaponStaffBall' then 
		--	weapon.Effects =
		end
	end

	table.insert(data.Weapons,
	{
		Name = "WeaponCastYM",
		InheritFrom = "1_BaseDamagingWeapon",
		Type = "GUN",
		Control = "Attack1",
		DefaultControl = false,
		Projectile = "ProjectileCastYM",
		ChargeSoundFadeTime = 0.25,
		RootOwnerWhileFiring = false,
		BlockMoveInput = false,
		CancelMovement = false,
		ChargeCancelMovement = false,
		ForceReleaseOnFire = true,
		FullyAutomatic = false,
		BarrelLength = 0,
		AutoLock = false,
		AutoLockRange = 1,
		RetainAimLocationWindow = 0.95,
		AutoLockArcDistance = 75,
		FireFx = "HecateMeleeFlare",
		ShowFreeAimLine = false,
		ChargeStartAnimation = "Melinoe_Cast_Start",
		OnlyChargeOnce = true,
		FireGraphic = "null",
		LockTriggerForCharge = true,
		SetTargetAngleOnRequest = false,
		FailedToFireCooldownDuration = 0.1,
		AllowExternalForceRelease = true,
		FireOnRelease = false,
		MinChargeToFire = 1.0,
		--ActiveProjectileCap = 2,
		ActiveProjectileCap = 1,
		AllowMultiFireRequest = true,
		ChargeCancelGraphic = "null",
		ChargeFinishFx = "null",
		Cooldown = 0.2,
		ChargeTimeFrames = 15,
		SwapOnFire = "null",
		AddOnFire = "WeaponCastArm",
		NumProjectiles = 1,
		WeaponRange = 1,
		ProjectileSpacing = 0,
		CanCancelDisables = true,
		IgnoreOwnerAttackDisabled = true,
		SetCompleteAngleOnFire = false,
		SetCompleteAngleOnCharge = false,
		LockTriggerTransferFromOnSwap = false,
		Strafe = false,
		IgnoreUnitChargeMultiplier = true,
		Effects =
		{       
			{
				Trigger = "Fire",
				Name = "CastInvulnerable",
				Type = "INVULNERABLE",
				Duration = 0.2,
				Modifier = 1.0,
				CanAffectInvulnerable = true,
				Active = false,
			},
			{
				Name = "WeaponCastAttackDisable",
				DurationFrames = 8,
				DisableMove = false,
				DisableRotate = false,
				DisableAttack = true,
				Cancelable = true,
				RequestTriggerLock = true,
				Active = true,
			},
			{
				Name = "WeaponCastSelfSlow",
				Trigger = "Charging",
				DurationFrames = 16,
				Type = "SPEED",
				Modifier = 0.60,
				Active = true,
			},
			{
				Name = "WeaponCastStop",
				Type = "SPEED",
				Modifier = 1.0,
				Duration = 0.1,
				HaltOnEnd = true,
				Active = false,
			},
		}
	})

	table.insert(data.Weapons,
	{
		Name = "WeaponCastHammerYM",
		InheritFrom = "1_BaseDamagingWeapon",
		Type = "GUN",
		Control = "Attack1",
		DefaultControl = false,
		Projectile = "ProjectileCastYM",
		ChargeSoundFadeTime = 0.25,
		RootOwnerWhileFiring = false,
		BlockMoveInput = false,
		CancelMovement = false,
		ChargeCancelMovement = false,
		ForceReleaseOnFire = true,
		FullyAutomatic = false,
		BarrelLength = 0,
		AutoLock = false,
		AutoLockRange = 1,
		RetainAimLocationWindow = 0.95,
		AutoLockArcDistance = 75,
		FireFx = "HecateMeleeFlare",
		ShowFreeAimLine = false,
		ChargeStartAnimation = "Melinoe_Cast_Start",
		OnlyChargeOnce = true,
		FireGraphic = "null",
		LockTriggerForCharge = true,
		SetTargetAngleOnRequest = false,
		FailedToFireCooldownDuration = 0.1,
		AllowExternalForceRelease = true,
		FireOnRelease = false,
		MinChargeToFire = 1.0,
		--ActiveProjectileCap = 2,
		ActiveProjectileCap = 1,
		AllowMultiFireRequest = true,
		ChargeCancelGraphic = "null",
		ChargeFinishFx = "null",
		Cooldown = 0.2,
		ChargeTimeFrames = 15,
		SwapOnFire = "null",
		AddOnFire = "WeaponCastArm",
		NumProjectiles = 1,
		WeaponRange = 1,
		ProjectileSpacing = 0,
		CanCancelDisables = true,
		IgnoreOwnerAttackDisabled = true,
		SetCompleteAngleOnFire = false,
		SetCompleteAngleOnCharge = false,
		LockTriggerTransferFromOnSwap = false,
		Strafe = false,
		IgnoreUnitChargeMultiplier = true,
		Effects =
		{       
			{
				Trigger = "Fire",
				Name = "CastInvulnerable",
				Type = "INVULNERABLE",
				Duration = 0.2,
				Modifier = 1.0,
				CanAffectInvulnerable = true,
				Active = false,
			},
			{
				Name = "WeaponCastAttackDisable",
				DurationFrames = 8,
				DisableMove = false,
				DisableRotate = false,
				DisableAttack = true,
				Cancelable = true,
				RequestTriggerLock = true,
				Active = true,
			},
			{
				Name = "WeaponCastSelfSlow",
				Trigger = "Charging",
				DurationFrames = 16,
				Type = "SPEED",
				Modifier = 0.60,
				Active = true,
			},
			{
				Name = "WeaponCastStop",
				Type = "SPEED",
				Modifier = 1.0,
				Duration = 0.1,
				HaltOnEnd = true,
				Active = false,
			},
		}
	})

	table.insert(data.Weapons,
	{
		Name = "WeaponCastArmYM",
		InheritFrom = "1_BaseDamagingWeapon",
		Control = "Attack1",
		Type = "GUN",
		Projectile = "null",
		ProjectileToArm = "ProjectileCastYM",
		LoseControlWithoutProjectile = "ProjectileCastYM",
		ChargeSoundFadeTime = 0.25,
		RootOwnerWhileFiring = false,
		BlockMoveInput = false,
		CancelMovement = false,
		ForceMaxChargeRelease = true,
		ChargeStartAnimation = "null",
		ChargeCancelGraphic = "null",
		FireGraphic = "Melinoe_Cast_Fire",
		TriggerReleaseGraphic = "null",
		ChargeCancelMovement = false,
		FullyAutomatic = true,
		BarrelLength = 0,
		AutoLock = false,
		AutoLockRange = 1,
		FireFx = "null",
		ShowFreeAimLine = false,
		LockTriggerForCharge = false,
		SetTargetAngleOnRequest = false,
		CancelChargeOnRelease = true,
		CancelChargeOnControlRemoved = true,
		ClearFireRequestOnChargeCancel = true,
		ForceReleaseWeaponOnFire = "WeaponCastYM",
		FireOnRelease = true,
		AllowExternalForceRelease = false,
		LoseControlOnRelease = true,
		AllowMultiFireRequest = false,
		LoseControlIfNotCharging = false,
		ChargeTime = 0.915,
		MinChargeToFire = 1.0,
		ChargeFinishFx = "null",
		Cooldown = 0.2,
		SwapOnFire = "WeaponCastYM",
		NumProjectiles = 1,
		ControlWindow = 0.1,
		WeaponRange = 1,
		ClipSize = 1,
		ClipRegenInterval = 0.2,
		ConsumeClipOnRelease = true,
		ProjectileSpacing = 0,
		CanCancelDisables = true,
		IgnoreOwnerAttackDisabled = false,
		SetCompleteAngleOnFire = false,
		SetCompleteAngleOnCharge = false,
		Strafe = false,
		IgnoreUnitChargeMultiplier = true,
		Effects =
		{ 
			{
				Name = "WeaponCastArmDisable",
				DurationFrames = 7,
				DisableMove = true,
				DisableRotate = false,
				DisableAttack = true,
				Cancelable = false,
				RequestTriggerLock = true,
				Active = true,
			},
			{
				Name = "WeaponCastArmDisableCancelable",
				DurationFrames = 15,
				DisableMove = false,
				DisableRotate = false,
				DisableAttack = true,
				Cancelable = true,
				RequestTriggerLock = true,
				Active = true,
			},
			{
				Trigger = "Charging",
				Name = "WeaponCastChargeMoveSlow",
				Type = "SPEED",
				Modifier = 0.60,
				Duration = 9999,
				HaltOnEnd = true,
				Active = true,
				Cancelable = true,
			},
		},
	})

	return data
	end)