--Dagger VFX
local file = rom.path.combine(rom.paths.Content, 'Game/Animations/Melinoe_Dagger_VFX.sjson')
sjson.hook(file, function(data)
	table.insert(data.Animations,
		{
		Name = "DaggerSwipeFastBrown",
		FilePath = "Fx\\DaggerSwipeFast\\DaggerSwipeFast",
		GroupName = "FX_Standing_Add",
		AddColor = true,
		ColorFromOwner = "Ignore",
		StartRed = 0.58,
		StartGreen = 0.29,
		StartBlue = 0.0,
		EndRed = 0.39,
		EndGreen = 0.26,
		EndBlue = 0.12,
		EndFrame = 19,
		NumFrames = 19,
		PlaySpeed = 75.0,
		StartFrame = 1,
		OriginX = 80.0,
		OriginY = 160.0,
		LocationFromOwner = "Take",
		LocationZFromOwner = "Take",
		PostRotateScaleY = 0.6,
		FlipHorizontal = false,
		Scale = 1.6,
		OffsetZ = 60,
		EaseIn = 0,
		EaseOut = 1,
		OverlayVfx = true,
		CreateAnimations =
		{
			{ Name = "DaggerSwipeFastDarkBrown" },
			{ Name = "DaggerSwipeFastLightBrown" }
		}
	})

	table.insert(data.Animations,
	{
		Name = "DaggerSwipeFastFlipBrown",
		InheritFrom = "DaggerSwipeFastBrown",
		FlipVertical = true,
		ClearCreateAnimations = true,
		CreateAnimations =
		{
			{ Name = "DaggerSwipeFastDarkFlipBrown" },
			{ Name = "DaggerSwipeFastLightBrown" }
		}
	})

	table.insert(data.Animations,
	{
	Name = "DaggerProjectileFxBrown",
	ChainTo = "null",
	FilePath = "Fx\\DaggerProjectile\\DaggerProjectile",
	GroupName = "Standing",
	ScaleFromOwner = "Ignore",
	VisualFx = "DaggerProjectileFxTrailBrown",
	EndFrame = 15,
	NumFrames = 15,
	RandomStartFrame = true,
	ReRandomizeOnLoop = false,
	StartFrame = 1,
	OriginY = 30.0,
	Scale = 0.75,
	ScaleY = 2,
	Ambient = 0.0,
	VisualFxDistanceMax = 100.0,
	VisualFxDistanceMin = 100.0,
	VisualFxManagerCap = 400,
	VisualFxManagerFrameCap = 18,
	VisualFxFrameCap = 10,
	ColorFromOwner = "Ignore",
	StartRed = 0.58,
	StartGreen = 0.29,
	StartBlue = 0.0,
	EndRed = 0.39,
	EndGreen = 0.26,
	EndBlue = 0.12,
	})

	table.insert(data.Animations,
	{
		Name = "DaggerProjectileFxTrailBrown",
		InheritFrom = "DaggerProjectileFxBrown",
		ColorFromOwner = "Ignore",
		ChainTo = "null",
		Sound = "null",
		FilePath = "Particles\\particle_dagger_trail_color",
		GroupName = "FX_Standing_Add",
		AngleFromOwner = "Take",
		AddColor = true,
		Duration = 0.33,
		EaseIn = 0.9,
		EaseOut = 1.0,
		EndFrame = 1,
		NumFrames = 1,
		StartFrame = 1,
		OriginY = 80.0,
		OriginX = 300,
		RandomOffsetY = 1.0,
		LocationFromOwner = "Take",
		LocationZFromOwner = "Take",
		VelocityMax = 200.0,
		VelocityMin = 100.0,
		EndScaleY = 0.0,
		ScaleY = 0.5,
		StartScaleY = 0.5,
		StartRed = 0.58,
		StartGreen = 0.29,
		StartBlue = 0.0,
		EndRed = 0.39,
		EndGreen = 0.26,
		EndBlue = 0.12,
		VisualFx = "DaggerProjectileCurvedTrailSparkle",
		VisualFxIntervalMin = 0.01,
		VisualFxIntervalMax = 0.50,
		VisualFxCap = 1,
		CreateAnimations =
		{
			{ Name = "DaggerProjectileFxTrailDarkBrown" },
			{ Name = "DaggerProjectileFxTrailSpectralBrown" },
			{ Name = "DaggerProjectileFxTrailDisplacementBrown" },
		},
	})

return data
end)

local file = rom.path.combine(rom.paths.Content, 'Game/Animations/Melinoe_Suit_VFX.sjson')
sjson.hook(file, function(data)
table.insert(data.Animations,
	{
	Name = "HarpyTornadoYM",
	FilePath = "Fx\\HarpyTornado\\HarpyTornado",
	NumFrames = 90,
	PlaySpeed = 60,
	Material = "Unlit",
	UseOwnAngle = false,
	AngleFromOwner = "Ignore",
	Loop = true,
	TransferFrameFromThis = true,
	ColorFromOwner = "Ignore",
	Scale = 0.5,
	OriginX = 320,
	OriginY = 256,
	Sound = "/Leftovers/Ambience/WhippingWindLoopLoud",
	StopSoundOnFinishFade = 0.2,
	ChainTo = "HarpyTornadoFadeYM",
	VisualFx = "ShipsDustTornado",
	VisualFxIntervalMin = 0.2,
	VisualFxIntervalMax = 0.4,
	AddColor = true,
	StartRed = 0.3,
	StartGreen = 0.01,
	StartBlue = 0.05,
	EndRed = 0.2,
	EndGreen = 0.03,
	EndBlue = 0.04,
	PingPongColor = true,
	})
	
	table.insert(data.Animations,
	{
	Name = "HarpyTornadoFadeYM",
	InheritFrom = "HarpyTornadoYM",
	TransferFrameToThis = true,
	Loop = false,
	LoopFramesOnly = true,
	StartAlpha = 1,
	EndAlpha = 0,
	Duration = 0.4,
	EaseIn = 0,
	EaseOut = 1,
	ChainTo = "null",
	Sound = "null",
	StartScale = 1.0, --// needs to match EndScale in HarpyFlap AIData
	EndScale = 1.2,
	PingPongColor = false,
	})

	table.insert(data.Animations,
	{
	Name = "HarpyTornadoYM_Zeus",
	FilePath = "Fx\\HarpyTornado\\HarpyTornado",
	NumFrames = 90,
	PlaySpeed = 60,
	Material = "Unlit",
	UseOwnAngle = false,
	AngleFromOwner = "Ignore",
	Loop = true,
	TransferFrameFromThis = true,
	ColorFromOwner = "Ignore",
	Scale = 0.5,
	OriginX = 320,
	OriginY = 256,
	Sound = "/Leftovers/Ambience/WhippingWindLoopLoud",
	StopSoundOnFinishFade = 0.2,
	ChainTo = "HarpyTornadoFadeYM_Zeus",
	VisualFx = "ShipsDustTornado",
	VisualFxIntervalMin = 0.2,
	VisualFxIntervalMax = 0.4,
	AddColor = true,
	StartRed = 1.0,
	StartGreen = 0.95,
	StartBlue = 0.7,
	EndRed = 0.9999,
	EndGreen = 0.8,
	EndBlue = 0.5,
	PingPongColor = true,
	})

	table.insert(data.Animations,
	{
	Name = "HarpyTornadoFadeYM_Zeus",
	InheritFrom = "HarpyTornadoYM_Zeus",
	TransferFrameToThis = true,
	Loop = false,
	LoopFramesOnly = true,
	StartAlpha = 1,
	EndAlpha = 0,
	Duration = 0.4,
	EaseIn = 0,
	EaseOut = 1,
	ChainTo = "null",
	Sound = "null",
	StartScale = 1.0, --// needs to match EndScale in HarpyFlap AIData
	EndScale = 1.2,
	PingPongColor = false,
	})

	table.insert(data.Animations,
	{
	Name = "HarpyTornadoYM_Poseidon",
	FilePath = "Fx\\HarpyTornado\\HarpyTornado",
	NumFrames = 90,
	PlaySpeed = 60,
	Material = "Unlit",
	UseOwnAngle = false,
	AngleFromOwner = "Ignore",
	Loop = true,
	TransferFrameFromThis = true,
	ColorFromOwner = "Ignore",
	Scale = 0.5,
	OriginX = 320,
	OriginY = 256,
	Sound = "/Leftovers/Ambience/WhippingWindLoopLoud",
	StopSoundOnFinishFade = 0.2,
	ChainTo = "HarpyTornadoFadeYM_Poseidon",
	VisualFx = "ShipsDustTornado",
	VisualFxIntervalMin = 0.2,
	VisualFxIntervalMax = 0.4,
	AddColor = true,
	StartRed = 0.1,
	StartGreen = 1.0,
	StartBlue = 0.8,
	EndRed = 0,
	EndGreen = 0.6,
	EndBlue = 1.0,
	PingPongColor = true,
	})

	table.insert(data.Animations,
	{
	Name = "HarpyTornadoFadeYM_Poseidon",
	InheritFrom = "HarpyTornadoYM_Poseidon",
	TransferFrameToThis = true,
	Loop = false,
	LoopFramesOnly = true,
	StartAlpha = 1,
	EndAlpha = 0,
	Duration = 0.4,
	EaseIn = 0,
	EaseOut = 1,
	ChainTo = "null",
	Sound = "null",
	StartScale = 1.0,
	EndScale = 1.2,
	PingPongColor = false,
	})
	
	table.insert(data.Animations,
	{
	Name = "HarpyTornadoYM_Hephaestus",
	FilePath = "Fx\\HarpyTornado\\HarpyTornado",
	NumFrames = 90,
	PlaySpeed = 60,
	Material = "Unlit",
	UseOwnAngle = false,
	AngleFromOwner = "Ignore",
	Loop = true,
	TransferFrameFromThis = true,
	ColorFromOwner = "Ignore",
	Scale = 0.5,
	OriginX = 320,
	OriginY = 256,
	Sound = "/Leftovers/Ambience/WhippingWindLoopLoud",
	StopSoundOnFinishFade = 0.2,
	ChainTo = "HarpyTornadoFadeYM_Hephaestus",
	VisualFx = "ShipsDustTornado",
	VisualFxIntervalMin = 0.2,
	VisualFxIntervalMax = 0.4,
	AddColor = true,
	StartRed = 0.51,
	StartGreen = 0.82,
	StartBlue = 1.00,
	EndRed = 1.00,
	EndGreen = 0,
	EndBlue = 0,
	PingPongColor = true,
	})
	
	table.insert(data.Animations,
	{
	Name = "HarpyTornadoFadeYM_Hephaestus",
	InheritFrom = "HarpyTornadoYM_Hephaestus",
	TransferFrameToThis = true,
	Loop = false,
	LoopFramesOnly = true,
	StartAlpha = 1,
	EndAlpha = 0,
	Duration = 0.4,
	EaseIn = 0,
	EaseOut = 1,
	ChainTo = "null",
	Sound = "null",
	StartScale = 1.0,
	EndScale = 1.2,
	PingPongColor = false,
	})

	table.insert(data.Animations,
	{
	Name = "HarpyTornadoYM_Hestia",
	FilePath = "Fx\\HarpyTornado\\HarpyTornado",
	NumFrames = 90,
	PlaySpeed = 60,
	Material = "Unlit",
	UseOwnAngle = false,
	AngleFromOwner = "Ignore",
	Loop = true,
	TransferFrameFromThis = true,
	ColorFromOwner = "Ignore",
	Scale = 0.5,
	OriginX = 320,
	OriginY = 256,
	Sound = "/Leftovers/Ambience/WhippingWindLoopLoud",
	StopSoundOnFinishFade = 0.2,
	ChainTo = "HarpyTornadoFadeYM_Hestia",
	VisualFx = "ShipsDustTornado",
	VisualFxIntervalMin = 0.2,
	VisualFxIntervalMax = 0.4,
	AddColor = true,
	StartRed = 1.0,
	StartGreen = 0.3,
	StartBlue = 0.02,
	EndRed = 0.999,
	EndGreen = 0.15,
	EndBlue = 0.0,
	PingPongColor = true,
	})

	table.insert(data.Animations,
	{
	Name = "HarpyTornadoFadeYM_Hestia",
	InheritFrom = "HarpyTornadoYM_Hestia",
	TransferFrameToThis = true,
	Loop = false,
	LoopFramesOnly = true,
	StartAlpha = 1,
	EndAlpha = 0,
	Duration = 0.4,
	EaseIn = 0,
	EaseOut = 1,
	ChainTo = "null",
	Sound = "null",
	StartScale = 1.0,
	EndScale = 1.2,
	PingPongColor = false,
	})
	
	table.insert(data.Animations,
	{
	Name = "HarpyTornadoYM_Hera",
	FilePath = "Fx\\HarpyTornado\\HarpyTornado",
	NumFrames = 90,
	PlaySpeed = 60,
	Material = "Unlit",
	UseOwnAngle = false,
	AngleFromOwner = "Ignore",
	Loop = true,
	TransferFrameFromThis = true,
	ColorFromOwner = "Ignore",
	Scale = 0.5,
	OriginX = 320,
	OriginY = 256,
	Sound = "/Leftovers/Ambience/WhippingWindLoopLoud",
	StopSoundOnFinishFade = 0.2,
	ChainTo = "HarpyTornadoFadeYM_Hera",
	VisualFx = "ShipsDustTornado",
	VisualFxIntervalMin = 0.2,
	VisualFxIntervalMax = 0.4,
	AddColor = true,
	StartRed = 0.0,
	StartGreen = 1.0,
	StartBlue = 0.1,
	EndRed = 0.1,
	EndGreen = 0.3,
	EndBlue = 1.0,
	PingPongColor = true,
	})

	table.insert(data.Animations,
	{
	Name = "HarpyTornadoFadeYM_Hera",
	InheritFrom = "HarpyTornadoYM_Hera",
	TransferFrameToThis = true,
	Loop = false,
	LoopFramesOnly = true,
	StartAlpha = 1,
	EndAlpha = 0,
	Duration = 0.4,
	EaseIn = 0,
	EaseOut = 1,
	ChainTo = "null",
	Sound = "null",
	StartScale = 1.0,
	EndScale = 1.2,
	PingPongColor = false,
	})

	table.insert(data.Animations,
	{
	Name = "HarpyTornadoYM_Apollo",
	FilePath = "Fx\\HarpyTornado\\HarpyTornado",
	NumFrames = 90,
	PlaySpeed = 60,
	Material = "Unlit",
	UseOwnAngle = false,
	AngleFromOwner = "Ignore",
	Loop = true,
	TransferFrameFromThis = true,
	ColorFromOwner = "Ignore",
	Scale = 0.5,
	OriginX = 320,
	OriginY = 256,
	Sound = "/Leftovers/Ambience/WhippingWindLoopLoud",
	StopSoundOnFinishFade = 0.2,
	ChainTo = "HarpyTornadoFadeYM_Apollo",
	VisualFx = "ShipsDustTornado",
	VisualFxIntervalMin = 0.2,
	VisualFxIntervalMax = 0.4,
	AddColor = true,
	StartRed = 1.0,
	StartGreen = 0.9,
	StartBlue = 0.7,
	EndRed = 0.999,
	EndGreen = 0.85,
	EndBlue = 0.05,
	PingPongColor = true,
	})

	table.insert(data.Animations,
	{
	Name = "HarpyTornadoFadeYM_Apollo",
	InheritFrom = "HarpyTornadoYM_Apollo",
	TransferFrameToThis = true,
	Loop = false,
	LoopFramesOnly = true,
	StartAlpha = 1,
	EndAlpha = 0,
	Duration = 0.4,
	EaseIn = 0,
	EaseOut = 1,
	ChainTo = "null",
	Sound = "null",
	StartScale = 1.0,
	EndScale = 1.2,
	PingPongColor = false,
	})

	table.insert(data.Animations,
	{
	Name = "HarpyTornadoYM_Aphrodite",
	FilePath = "Fx\\HarpyTornado\\HarpyTornado",
	NumFrames = 90,
	PlaySpeed = 60,
	Material = "Unlit",
	UseOwnAngle = false,
	AngleFromOwner = "Ignore",
	Loop = true,
	TransferFrameFromThis = true,
	ColorFromOwner = "Ignore",
	Scale = 0.5,
	OriginX = 320,
	OriginY = 256,
	Sound = "/Leftovers/Ambience/WhippingWindLoopLoud",
	StopSoundOnFinishFade = 0.2,
	ChainTo = "HarpyTornadoFadeYM_Aphrodite",
	VisualFx = "ShipsDustTornado",
	VisualFxIntervalMin = 0.2,
	VisualFxIntervalMax = 0.4,
	AddColor = true,
	StartRed = 1.0,
	StartGreen = 0.6,
	StartBlue = 0.8,
	EndRed = 0.99,
	EndGreen = 0.05,
	EndBlue = 0.99,
	PingPongColor = true,
	})

	table.insert(data.Animations,
	{
	Name = "HarpyTornadoFadeYM_Aphrodite",
	InheritFrom = "HarpyTornadoYM_Aphrodite",
	TransferFrameToThis = true,
	Loop = false,
	LoopFramesOnly = true,
	StartAlpha = 1,
	EndAlpha = 0,
	Duration = 0.4,
	EaseIn = 0,
	EaseOut = 1,
	ChainTo = "null",
	Sound = "null",
	StartScale = 1.0, --// needs to match EndScale in HarpyFlap AIData
	EndScale = 1.2,
	PingPongColor = false,
	})

	table.insert(data.Animations,
	{
	Name = "HarpyTornadoYM_Ares",
	FilePath = "Fx\\HarpyTornado\\HarpyTornado",
	NumFrames = 90,
	PlaySpeed = 60,
	Material = "Unlit",
	UseOwnAngle = false,
	AngleFromOwner = "Ignore",
	Loop = true,
	TransferFrameFromThis = true,
	ColorFromOwner = "Ignore",
	Scale = 0.5,
	OriginX = 320,
	OriginY = 256,
	Sound = "/Leftovers/Ambience/WhippingWindLoopLoud",
	StopSoundOnFinishFade = 0.2,
	ChainTo = "HarpyTornadoFadeYM_Ares",
	VisualFx = "ShipsDustTornado",
	VisualFxIntervalMin = 0.2,
	VisualFxIntervalMax = 0.4,
	AddColor = true,
	StartRed = 1.0,
	StartGreen = 0.04,
	StartBlue = 0.001,
	EndRed = 0.999,
	EndGreen = 0.0,
	EndBlue = 0.0,
	PingPongColor = true,
	})

	table.insert(data.Animations,
	{
	Name = "HarpyTornadoFadeYM_Ares",
	InheritFrom = "HarpyTornadoYM_Ares",
	TransferFrameToThis = true,
	Loop = false,
	LoopFramesOnly = true,
	StartAlpha = 1,
	EndAlpha = 0,
	Duration = 0.4,
	EaseIn = 0,
	EaseOut = 1,
	ChainTo = "null",
	Sound = "null",
	StartScale = 1.0, --// needs to match EndScale in HarpyFlap AIData
	EndScale = 1.2,
	PingPongColor = false,
	})

	table.insert(data.Animations,
	{
	Name = "HarpyTornadoYM_Demeter",
	FilePath = "Fx\\HarpyTornado\\HarpyTornado",
	NumFrames = 90,
	PlaySpeed = 60,
	Material = "Unlit",
	UseOwnAngle = false,
	AngleFromOwner = "Ignore",
	Loop = true,
	TransferFrameFromThis = true,
	ColorFromOwner = "Ignore",
	Scale = 0.5,
	OriginX = 320,
	OriginY = 256,
	Sound = "/Leftovers/Ambience/WhippingWindLoopLoud",
	StopSoundOnFinishFade = 0.2,
	ChainTo = "HarpyTornadoFadeYM_Demeter",
	VisualFx = "ShipsDustTornado",
	VisualFxIntervalMin = 0.2,
	VisualFxIntervalMax = 0.4,
	AddColor = true,
	StartRed = 0.25,
	StartGreen = 0.35,
	StartBlue = 0.5,
	EndRed = 0.35,
	EndGreen = 0.25,
	EndBlue = 0.4999,
	PingPongColor = true,
	})

	table.insert(data.Animations,
	{
	Name = "HarpyTornadoFadeYM_Demeter",
	InheritFrom = "HarpyTornadoYM_Demeter",
	TransferFrameToThis = true,
	Loop = false,
	LoopFramesOnly = true,
	StartAlpha = 1,
	EndAlpha = 0,
	Duration = 0.4,
	EaseIn = 0,
	EaseOut = 1,
	ChainTo = "null",
	Sound = "null",
	StartScale = 1.0, --// needs to match EndScale in HarpyFlap AIData
	EndScale = 1.2,
	PingPongColor = false,
	})

	table.insert(data.Animations,
	{
		Name = "MageProjectileExplosion_LightRangedYM",
		InheritFrom = "MageProjectileExplosion",
		Scale = 1,
		GroupName = "FX_Standing_Add",
		RandomRotation = false,
		UseOwnAngle = false,
		OffsetZ = 20,
		VisualFx = "EnemyProjectileImpactParticles",
		VisualFxCap = 3,
		VisualFxIntervalMin = 0.01,
		VisualFxIntervalMax = 0.01,
		CreateAnimations =
		{
			{ Name = "MageProjectileExplosionGlow" },
			{ Name = "MageProjectileExplosionDark_LightRanged" },
		},
	})

	table.insert(data.Animations,
	{
		Name = "MageProjectileExplosion_LightRangedYM_Zeus",
		InheritFrom = "MageProjectileExplosion_LightRangedYM",
		AddColor = true,
		StartRed = 1.0,
		StartGreen = 0.95,
		StartBlue = 0.7,
		EndRed = 0.9999,
		EndGreen = 0.8,
		EndBlue = 0.5,
		CreateAnimations =
		{
			{ Name = "MageProjectileExplosionGlow" },
			{ Name = "MageProjectileExplosionDark_LightRanged" },
		},
	})

return data
end)